### ISSUE TITLE
Installation on magento 2.3.5-p1

### ISSUE THREAD

**Issue by ommartins** [mageplaza/magento-2-better-maintenance#8]
Hi team,
I've tried to install the extension on my magento 2.3.5-p1 but I got an empty page on stores/installation/Mageplaza Extensions/Better Maintenance. 
In the system.log file I get: main.CRITICAL: User Deprecated Functionality: Session ID is not used as URL parameter anymore.
Do you have any fix?

Kind regards,
Oscar

**Comment by toandt98** [comment]
Hello,

Thank you for contacting us.
We have received your notice and have fixed this issue.
Please refer this commit: 7c78f08

Best Regards,
​Uri

**Comment by grzegorzrzeznikiewicz** [comment]
Hello, I also have a problem with this extension and magento 2.3.5-p1. After installation, of course module is enabled in config.php, I configured in admin panel, cache cleared/flushed, same for redis. The problem is that after enabling maintenance mode this module is not working - I have default magento maintenance site/message. Do I need something more to activate this module?
